Add tests for helper functions
x-team/GamesHQ-FE pull request #22
Opened 2024-10-17 10:57 UTC by deepansh946

## Fixes
https://x-team-internal.atlassian.net/browse/CORE-2611

## How to test
- Run `npm run test` 
- It should pass without any errors.

## Screenshots

![Screenshot 2024-10-17 at 4 26 50 PM](https://github.com/user-attachments/assets/201337e7-12c9-4b39-a977-23ab89cf2c88)

2024-10-21 13:59 UTC, nicksp requested changes

2024-10-21 13:59 UTC, nicksp commented on src/__tests__/signInAndOutHelper.test.ts
> +import { handleLogoutClick } from "../helpers/signInAndOutHelper";
@deepansh946 I highly suggest we keep test files colocated with their respective modules for ease of navigation and to easier spot what's tested and what is not.

2024-10-22 11:37 UTC, nicksp commented on src/__tests__/signInAndOutHelper.test.ts
> +import { handleLogoutClick } from "../helpers/signInAndOutHelper";
@deepansh946 I meant not moving the test folder but keeping the test files next to the modules they test so it's easy to spot which file has a corresponding test and which isn't without looking into nested folder.

2024-10-22 11:38 UTC, nicksp requested changes
Let's keep the test files colocated with their modules along each other for convenience.

2024-10-23 17:17 UTC, nicksp approved these changes

2024-10-29 13:59 UTC, kengru approved these changes

2024-11-01 20:17 UTC, nicksp commented
@deepansh946 Please resolve merge conflicts.

2024-11-04 13:23 UTC, nicksp commented
@deepansh946 It's Ready to merge 🙌

2024-11-05 05:46 UTC, merged