Add unit tests for hooks
x-team/GamesHQ-FE pull request #26
Opened 2024-10-22 04:40 UTC by deepansh946

Fixes:

https://x-team-internal.atlassian.net/browse/CORE-2618

2024-10-22 20:03 UTC, nicksp requested changes

2024-10-22 20:03 UTC, nicksp commented on src/hooks/__tests__/useCurrentUser.test.tsx
> +import { renderHook, act } from '@testing-library/react-hooks';
Let's please keep tests next to the files they're testing so it's easier to navigate and explore what's not tested.

2024-10-23 17:21 UTC, nicksp approved these changes

2024-10-29 13:59 UTC, kengru approved these changes

2024-11-01 20:18 UTC, nicksp commented
@deepansh946 Please resolve merge conflicts.

2024-11-04 13:23 UTC, nicksp commented
Feel free to merge this @deepansh946 🚀

2024-11-05 05:56 UTC, merged